name: Deploy test

on:
  push:
    branches:
      - main  # Hoặc tên nhánh bạn muốn deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # hoặc phiên bản bạn cần

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build  # Make sure bạn có script "build" trong package.json

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # hoặc ./dist nếu bạn dùng Vite
